# Generated by Django 2.0.7 on 2018-07-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='checkbox_bool',
            field=models.BooleanField(default=True),
        ),
    ]
